"use client";
import {useEffect,useRef,useState} from "react";
import {supabase} from "@/lib/supabase";
import {ANNOUNCEMENT_TEMPLATES,ANNOUNCEMENT_AUDIENCES,PERSONALIZATION_KEYS,TEMPLATE_CATEGORIES,personalize,scheduleInstant,normalizeAnnouncement,singleEmail,type AnnouncementAudience,type AnnouncementContact,type AnnouncementDraft,type AnnouncementKind} from "@/lib/company-announcements";
const field="w-full rounded-xl border border-[#d9ccbb] bg-white px-3 py-2 text-sm";
const button="rounded-xl border border-[#d9ccbb] bg-white px-4 py-2 text-sm disabled:opacity-50";
const audienceLabels:Record<AnnouncementAudience,string>={ALL:"Everyone",OWNERS:"Owners",CLEANERS:"Cleaners",GROUNDS:"Grounds staff",ADMINS:"Admins"};
type Campaign={id:string;kind:AnnouncementKind;category:string;audience:AnnouncementAudience;subject:string;message:string;link_url:string;link_label:string;revision:number;status:string;created_at:string;scheduled_at:string|null;schedule_timezone:string;selection_keys:string[]|null;exclusion_summary:Record<string,number>;counts?:Record<string,number>;queued_at?:string;sender_name?:string};
type Template=Pick<Campaign,"id"|"kind"|"category"|"subject"|"message"|"link_url"|"link_label"|"revision"|"created_at">&{name:string;updated_at:string;created_by:string;updated_by:string};
type Recipient={id:string;recipient_key:string;recipient_role:string;email:string;full_name:string;status:string;attempts:number;last_error:string|null;last_attempted_at:string|null;retry_succeeded_at:string|null;next_attempt_at:string;sent_at:string|null};
type Detail={announcement:Campaign;recipients:Recipient[];counts:Record<string,number>;review:{eligible:number;optedOut:number;unavailable:number};companyName:string};
const label=(value:string)=>value.toLowerCase().replaceAll("_"," ");
const roleLabels:Record<string,string>={OWNERS:"Owner",CLEANERS:"Cleaner",GROUNDS:"Grounds staff",ADMINS:"Admin"};
async function api(org:string,body?:unknown,id?:string,filters?:Record<string,string>) {
  const {data}=await supabase.auth.getSession();
  const params=new URLSearchParams({organizationId:org,...(id?{id}:{}),...filters});
  const r=await fetch(`/api/admin/company-announcements?${params}`,{method:body?"POST":"GET",headers:{Authorization:`Bearer ${data.session?.access_token||""}`,"Content-Type":"application/json"},body:body?JSON.stringify({organizationId:org,...body as object}):undefined,cache:"no-store"});
  const result=await r.json();if(!r.ok)throw new Error(result.error||"Could not load announcements.");return result;
}
export default function CompanyAnnouncements({organizationId,onDirtyChange}:{organizationId:string;onDirtyChange?:(dirty:boolean)=>void}) {
  const [contacts,setContacts]=useState<AnnouncementContact[]>([]),[history,setHistory]=useState<Campaign[]>([]),[optedOut,setOptedOut]=useState<string[]>([]);
  const [draft,setDraft]=useState<AnnouncementDraft>({...ANNOUNCEMENT_TEMPLATES.ANNOUNCEMENT}),[audience,setAudience]=useState<AnnouncementAudience>("ALL");
  const [mode,setMode]=useState<"GROUP"|"SELECTED">("GROUP"),[selected,setSelected]=useState<string[]>([]),[query,setQuery]=useState("");
  const [detail,setDetail]=useState<Detail|null>(null),[dirty,setDirty]=useState(false),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState(""),[message,setMessage]=useState("");
  const mounted=useRef(true);
  const [templates,setTemplates]=useState<Template[]>([]),[templateId,setTemplateId]=useState(""),[templateName,setTemplateName]=useState(""),[category,setCategory]=useState<string>("GENERAL");
  const [timezone,setTimezone]=useState("America/Toronto"),[sendMode,setSendMode]=useState("NOW"),[scheduledLocal,setScheduledLocal]=useState(""),[emailEnabled,setEmailEnabled]=useState(false);
  const [filters,setFilters]=useState<Record<string,string>>({}),[offset,setOffset]=useState(0),[hasMore,setHasMore]=useState(false);
  const testIdentity=useRef<string|null>(null);
  function loadList(r:{contacts:AnnouncementContact[];announcements:Campaign[];optedOut:string[];templates:Template[];timezone:string;emailEnabled:boolean;historyHasMore:boolean}){setContacts(r.contacts||[]);setHistory(r.announcements||[]);setOptedOut(r.optedOut||[]);setTemplates(r.templates||[]);setEmailEnabled(r.emailEnabled);setHasMore(r.historyHasMore);}
  useEffect(()=>{mounted.current=true;api(organizationId).then(r=>{if(mounted.current){loadList(r);setTimezone(r.timezone||"America/Toronto");}}).catch(e=>{if(mounted.current)setError(e.message);}).finally(()=>{if(mounted.current)setLoading(false);});return()=>{mounted.current=false;};},[organizationId]);
  useEffect(()=>{onDirtyChange?.(dirty);},[dirty,onDirtyChange]);
  useEffect(()=>{if(!dirty)return;const warn=(e:BeforeUnloadEvent)=>{e.preventDefault();e.returnValue="";};window.addEventListener("beforeunload",warn);return()=>window.removeEventListener("beforeunload",warn);},[dirty]);
  const locked=!!detail&&detail.announcement.status!=="DRAFT";
  const groupContacts=contacts.filter(c=>audience==="ALL"||c.audience===audience);
  const eligible=groupContacts.filter(c=>singleEmail(c.email)&&!optedOut.includes(c.email));
  const visible=groupContacts.filter(c=>`${c.full_name} ${c.email}`.toLowerCase().includes(query.toLowerCase()));
  function edit(change:Partial<AnnouncementDraft>){setDraft(d=>({...d,...change}));setDirty(true);testIdentity.current=null;setMessage("");}
  async function refresh(id:string){const r:Detail=await api(organizationId,undefined,id);if(mounted.current)setDetail(r);return r;}
  async function refreshHistory(page=offset){const r=await api(organizationId,undefined,undefined,{...filters,offset:String(page)});if(mounted.current){loadList(r);setOffset(page);}}
  async function save() {
    setBusy(true);setError("");setMessage("");
    try{const checked=normalizeAnnouncement(draft,true);const r=await api(organizationId,{action:"save",id:detail?.announcement.id,revision:detail?.announcement.revision||0,draft:checked,category,audience,recipientKeys:mode==="GROUP"?null:selected});await refresh(r.id);setDraft(checked);setDirty(false);await refreshHistory();setMessage("Draft saved. Review the message and exact recipient count below before sending.");}
    catch(e){setError((e as Error).message);}finally{setBusy(false);}
  }
  async function process(id:string,retry=false) {
    if(retry)await api(organizationId,{action:"retry",id});
    while(mounted.current) {const r=await api(organizationId,{action:"process",id});await refresh(id);if(r.processed===0)break;}
    if(mounted.current){await refreshHistory();setMessage("Processing finished for recipients currently due. Provider-accepted messages are listed below; retries and items requiring review stay visible.");}
  }
  async function send() {
    if(!detail||dirty)return;
    const count=detail.review?.eligible??detail.counts.DRAFT??0;
    setBusy(true);setError("");setMessage("");
    try{normalizeAnnouncement(draft);const scheduledAt=sendMode==="LATER"?scheduleInstant(scheduledLocal,timezone):null;if(!window.confirm(`${scheduledAt?`Schedule for ${scheduledLocal} (${timezone})`:"Send now"}: “${draft.subject}” to ${count} separate addresses?${count>=500?" Large audience: check the recipient list carefully.":""}`))return;await api(organizationId,{action:scheduledAt?"schedule":"send",id:detail.announcement.id,revision:detail.announcement.revision,confirm:true,scheduledAt,timezone});await refresh(detail.announcement.id);if(scheduledAt){await refreshHistory();setMessage("Schedule saved. Delivery runs through the configured server worker; you can close this page.");}else await process(detail.announcement.id);}
    catch(e){setError((e as Error).message);}finally{if(mounted.current)setBusy(false);}
  }
  async function open(c:Campaign) {
    if(dirty&&!window.confirm("Discard unsaved announcement changes?"))return;
    setBusy(true);setError("");setMessage("");
    try{const r=await refresh(c.id);restore(r);}
    catch(e){setError((e as Error).message);}finally{setBusy(false);}
  }
  function restore(r:Detail){const c=r.announcement;setDraft({kind:c.kind,subject:c.subject,message:c.message,linkUrl:c.link_url,linkLabel:c.link_label});setCategory(c.category);setTimezone(c.schedule_timezone||"America/Toronto");setAudience(c.audience);setMode(c.selection_keys===null?"GROUP":"SELECTED");setSelected(c.selection_keys||[]);setDirty(false);testIdentity.current=null;setTemplateId("");}
  function newDraft(){if(dirty&&!window.confirm("Discard unsaved announcement changes?"))return;setDetail(null);setDraft({kind:"ANNOUNCEMENT",subject:"",message:"",linkUrl:"",linkLabel:""});setCategory("GENERAL");setTemplateId("");setTemplateName("");setAudience("ALL");setMode("GROUP");setSelected([]);setDirty(false);setError("");setMessage("");testIdentity.current=null;}
  async function action(body:object,success:string){setBusy(true);setError("");try{const r=await api(organizationId,body);await refreshHistory();setMessage(success);return r;}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  async function templateAction(operation:string,existing=false){const t=templates.find(t=>t.id===templateId);if(existing&&!t)return;if(operation==="archive"&&!window.confirm(`Archive “${t?.name}”? Existing broadcasts are preserved.`))return;const r=await action({action:"template",operation,id:existing?t?.id:undefined,revision:existing?t?.revision:0,name:templateName,category,draft},"Template saved. Templates never store recipient lists.");if(r&&(operation==="save"||operation==="duplicate"))setTemplateId(r.id);if(r&&operation==="archive")setTemplateId("");}
  function applyTemplate(id:string){const t=templates.find(t=>t.id===id);if(!t)return;if(dirty&&!window.confirm("Replace unsaved content with this template?"))return;setDetail(null);setTemplateId(id);setTemplateName(t.name);setDraft({kind:t.kind,subject:t.subject,message:t.message,linkUrl:t.link_url,linkLabel:t.link_label});setCategory(t.category);setAudience("ALL");setMode("GROUP");setSelected([]);setDirty(true);testIdentity.current=null;setMessage("Template applied to a new draft. Choose and review its audience before sending.");}
  async function sendTest(){try{normalizeAnnouncement(draft);}catch(e){setError((e as Error).message);return;}testIdentity.current||=crypto.randomUUID();await action({action:"test",draft,requestId:testIdentity.current},"Test accepted by the provider for your signed-in admin email. Broadcast totals are unchanged.");}
  async function campaignAction(kind:string){if(!detail)return;if(kind==="duplicate"&&dirty&&!window.confirm("Discard unsaved changes and duplicate the saved broadcast?"))return;if(kind==="cancel"&&!window.confirm("Cancel this schedule before sending starts?"))return;const r=await action({action:kind,id:detail.announcement.id,revision:detail.announcement.revision},kind==="duplicate"?"New draft created. Choose recipients and save before confirmation.":kind==="cancel"?"Schedule cancelled.":"Returned to draft. Save changes and confirm a new schedule.");if(r){try{const d=await refresh(kind==="duplicate"?r.id:detail.announcement.id);restore(d);}catch(e){setError((e as Error).message);}}}
  const previewRecipient=detail?.recipients[0];
  const previewValues={name:previewRecipient?.full_name,role:roleLabels[previewRecipient?.recipient_role||""]};
  const preview=(value:string)=>personalize(value,previewValues,detail?.companyName||"");
  if(loading)return <p className="p-5 text-sm">Loading company announcements…</p>;
  return <section className="space-y-6" aria-label="Company announcements">
    <div className="rounded-[24px] border border-[#eadfce] bg-white p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-xl font-semibold">Company announcements</h2><p className="mt-2 max-w-3xl text-sm text-[#7f7263]">Send updates, surveys, or testimonial requests to everyone, an audience group, or selected people. Each email goes to one address, with no CC or BCC. Replies go to your company reply-to address.</p></div><button className={button} disabled={busy} onClick={newDraft}>New message</button></div></div>
    {error&&<p role="alert" className="rounded-xl bg-red-50 p-4 text-sm text-red-800">{error}</p>}{message&&<p role="status" className="rounded-xl bg-green-50 p-4 text-sm text-green-800">{message}</p>}
    {!emailEnabled&&<p className="rounded-xl border bg-amber-50 p-4 text-sm">Live email is disabled. Drafts, templates, previews, and schedules can be prepared; delivery requires approved email configuration and a server worker.</p>}
    <div className="grid items-start gap-6 lg:grid-cols-[minmax(0,1fr)_320px]">
      <div className="space-y-5 rounded-[24px] border border-[#eadfce] bg-white p-5"><h3 className="font-semibold">{locked?label(detail!.announcement.status):"Compose message"}</h3>
        <details className="space-y-3"><summary className="cursor-pointer text-sm font-semibold">Organization templates</summary><select aria-label="Start from template" className={field} disabled={busy} value={templateId} onChange={e=>applyTemplate(e.target.value)}><option value="">Choose a template to start a new draft</option>{templates.map(t=><option key={t.id} value={t.id}>{t.name} · {label(t.category)}</option>)}</select><input aria-label="Template name" className={field} placeholder="Template name" maxLength={150} value={templateName} onChange={e=>setTemplateName(e.target.value)}/><div className="flex flex-wrap gap-2"><button className={button} disabled={busy||!templateName.trim()} onClick={()=>void templateAction("save")}>Save as new template</button>{templateId&&<><button className={button} disabled={busy||!templateName.trim()} onClick={()=>void templateAction("save",true)}>Update template</button><button className={button} disabled={busy} onClick={()=>void templateAction("duplicate",true)}>Duplicate template</button><button className={button} disabled={busy} onClick={()=>void templateAction("archive",true)}>Archive template</button></>}</div>{templates.find(t=>t.id===templateId)&&<p className="text-xs text-[#7f7263]">Last updated {new Date(templates.find(t=>t.id===templateId)!.updated_at).toLocaleString()}. Organization admins can manage these templates. No audience is saved.</p>}</details>
        <fieldset disabled={busy||locked} className="space-y-4 disabled:opacity-70">
          <div className="grid gap-4 sm:grid-cols-2"><label className="space-y-1 text-sm"><span>Message type</span><select className={field} value={draft.kind} onChange={e=>{const kind=e.target.value as AnnouncementKind;edit({...ANNOUNCEMENT_TEMPLATES[kind]});}}><option value="ANNOUNCEMENT">Company update</option><option value="SURVEY">Survey invitation</option><option value="TESTIMONIAL">Testimonial request</option></select></label><label className="space-y-1 text-sm"><span>Audience</span><select className={field} value={audience} onChange={e=>{setAudience(e.target.value as AnnouncementAudience);setSelected([]);setDirty(true);}}>{ANNOUNCEMENT_AUDIENCES.map(a=><option key={a} value={a}>{audienceLabels[a]}</option>)}</select></label></div>
          <label className="block space-y-1 text-sm"><span>Template category</span><select className={field} value={category} onChange={e=>{setCategory(e.target.value);setDirty(true);}}>{TEMPLATE_CATEGORIES.map(c=><option key={c} value={c}>{label(c)}</option>)}</select></label>
          <div className="flex flex-wrap gap-4 text-sm"><label><input type="radio" checked={mode==="GROUP"} onChange={()=>{setMode("GROUP");setDirty(true);}}/> All in this audience</label><label><input type="radio" checked={mode==="SELECTED"} onChange={()=>{setMode("SELECTED");setDirty(true);}}/> Choose individuals</label></div>
          <p className="text-xs text-[#7f7263]">Duplicate addresses receive one email. Missing/invalid addresses and people who opted out are excluded. Saving calculates the exact recipients from your organization.</p>
          {mode==="SELECTED"&&<div className="space-y-2"><input aria-label="Search recipients" className={field} placeholder="Search name or email" value={query} onChange={e=>setQuery(e.target.value)}/><div className="max-h-64 space-y-2 overflow-auto rounded-xl border p-3">{visible.map(c=>{const usable=eligible.includes(c);return <label key={c.recipient_key} className="flex items-start gap-2 text-sm"><input disabled={!usable} type="checkbox" checked={selected.includes(c.recipient_key)} onChange={e=>{setSelected(s=>e.target.checked?[...s,c.recipient_key]:s.filter(id=>id!==c.recipient_key));setDirty(true);}}/><span>{c.full_name||c.email}<span className="block text-xs text-[#7f7263]">{c.email} · {audienceLabels[c.audience]}{!usable?" · Unavailable or opted out":""}</span></span></label>;})}{!visible.length&&<p className="text-sm">No matching contacts.</p>}</div>{contacts.length===1000&&<p className="text-xs">Individual selection shows the first 1,000 contacts. “All in this audience” includes every eligible contact.</p>}</div>}
          <label className="block space-y-1 text-sm"><span>Subject</span><input className={field} maxLength={200} value={draft.subject} onChange={e=>edit({subject:e.target.value})}/></label>
          <label className="block space-y-1 text-sm"><span>Message</span><textarea className={field} rows={9} maxLength={20000} value={draft.message} onChange={e=>edit({message:e.target.value})}/><span className="text-xs text-[#7f7263]">Plain text. A greeting is added unless your message uses a name variable.</span></label>
          <div className="space-y-2 text-xs"><p>Personalization variables work in subject, message, and button label. Missing names fall back to “there”.</p><div className="flex flex-wrap gap-2">{PERSONALIZATION_KEYS.map(k=><button type="button" key={k} className={button} onClick={()=>edit({message:`${draft.message}{{${k}}}`})}>{`{{${k}}}`}</button>)}</div></div>
          <div className="grid gap-4 sm:grid-cols-2"><label className="space-y-1 text-sm"><span>{draft.kind==="ANNOUNCEMENT"?"Optional link":"Survey / testimonial form link"}</span><input className={field} placeholder="https://…" value={draft.linkUrl} onChange={e=>edit({linkUrl:e.target.value})}/></label><label className="space-y-1 text-sm"><span>Link button label</span><input className={field} maxLength={100} value={draft.linkLabel} onChange={e=>edit({linkLabel:e.target.value})}/></label></div>
        </fieldset>
        <div className="flex flex-wrap gap-2">{!locked&&<button className={button} disabled={busy} onClick={()=>void save()}>{busy?"Working…":"Save draft & preview"}</button>}<button className={button} disabled={busy||!emailEnabled} onClick={()=>void sendTest()}>Send test to myself</button>{detail&&<button className={button} disabled={busy} onClick={()=>void campaignAction("duplicate")}>Duplicate broadcast</button>}</div>{dirty&&<p className="text-xs text-amber-800">Unsaved changes. Save your draft before leaving; incomplete drafts can be saved.</p>}
        {detail&&!dirty&&<div className="space-y-4 border-t pt-5"><h3 className="font-semibold">{locked?"Message preview":"Review before sending"}</h3><p className="text-sm">Audience: {audienceLabels[detail.announcement.audience]} · {Object.values(detail.counts).reduce((a,b)=>a+b,0)} separate recipients · EMAIL</p>{!locked&&<p className="text-sm">Currently eligible: {detail.review?.eligible??detail.counts.DRAFT??0}. Newly opted out: {detail.review?.optedOut||0}; unavailable: {detail.review?.unavailable||0}.</p>}<p className="text-sm">Excluded before snapshot: {detail.announcement.exclusion_summary?.optedOut||0} opted out, {detail.announcement.exclusion_summary?.invalid||0} missing/invalid addresses. Eligibility is checked again before delivery.</p>{(detail.counts.DRAFT||0)>=500&&<p className="text-sm text-amber-800">Large audience. Review the recipient list carefully.</p>}{!locked&&!(detail.review?.eligible??detail.counts.DRAFT)&&<p role="alert" className="text-sm text-amber-800">No eligible recipients remain. Choose an audience and save again.</p>}<p className="text-xs">Personalization: {/{{/.test(draft.subject+draft.message+draft.linkLabel)?"enabled":"automatic greeting"}. Preview uses {previewRecipient?.full_name||"fallback values"}.</p><div className="rounded-2xl border bg-[#fcfaf7] p-5"><p className="mb-5 text-sm"><strong>Subject:</strong> {preview(detail.announcement.subject)||"Subject is required before sending"}</p>{!/{{\s*(first_name|full_name)\s*}}/.test(draft.message)&&<p className="mb-4">{previewRecipient?.full_name?`Hello ${previewRecipient.full_name},`:"Hello,"}</p>}<p className="whitespace-pre-wrap leading-7">{preview(detail.announcement.message)||"Message is required before sending"}</p>{detail.announcement.link_url&&<a className="mt-5 inline-block rounded-xl bg-[#241c15] px-4 py-3 text-sm text-white" href={detail.announcement.link_url} target="_blank" rel="noopener noreferrer">{preview(detail.announcement.link_label)}</a>}<p className="mt-5 text-xs text-[#7f7263]">Company signature and an email preferences link are included in each message.</p></div>
          {!locked&&<div className="space-y-3"><label className="block text-sm">Send <select className={field} value={sendMode} onChange={e=>setSendMode(e.target.value)}><option value="NOW">Now</option><option value="LATER">Schedule for later</option></select></label>{sendMode==="LATER"&&<div className="grid gap-3 sm:grid-cols-2"><label className="text-sm">Date and local time<input className={field} type="datetime-local" value={scheduledLocal} onChange={e=>setScheduledLocal(e.target.value)}/></label><label className="text-sm">Timezone<input className={field} value={timezone} onChange={e=>setTimezone(e.target.value)}/></label></div>}<button className={`${button} bg-[#241c15] text-white`} disabled={busy||!(detail.review?.eligible??detail.counts.DRAFT)||(sendMode==="NOW"&&!emailEnabled)||!draft.subject.trim()||!draft.message.trim()} onClick={()=>void send()}>{sendMode==="LATER"?"Confirm schedule":"Confirm & send individually"}</button></div>}
          {detail.announcement.status==="SCHEDULED"&&<div className="space-y-3"><p className="text-sm">Scheduled: {new Date(detail.announcement.scheduled_at!).toLocaleString(undefined,{timeZone:detail.announcement.schedule_timezone})} ({detail.announcement.schedule_timezone})</p><div className="flex gap-2"><button className={button} disabled={busy} onClick={()=>void campaignAction("editSchedule")}>Edit scheduled broadcast</button><button className={button} disabled={busy} onClick={()=>void campaignAction("cancel")}>Cancel schedule</button></div></div>}
          {locked&&<><div className="flex flex-wrap gap-2 text-xs">{Object.entries(detail.counts).map(([status,n])=><span key={status} className="rounded-full border px-3 py-1">{status==="SENT"?"Accepted by email provider":status==="REVIEW"?"Needs review":status.toLowerCase()}: {n}</span>)}</div><div className="flex flex-wrap gap-2"><button className={button} disabled={busy||!emailEnabled||!["SENDING","QUEUED"].includes(detail.announcement.status)} onClick={()=>{setBusy(true);setError("");void process(detail.announcement.id).catch(e=>setError(e.message)).finally(()=>setBusy(false));}}>Process queued emails</button>{!!detail.counts.FAILED&&<button className={button} disabled={busy||!emailEnabled} onClick={()=>{setBusy(true);setError("");void process(detail.announcement.id,true).catch(e=>setError(e.message)).finally(()=>setBusy(false));}}>Retry failed emails</button>}<button className={button} disabled={busy} onClick={()=>void refresh(detail.announcement.id).catch(e=>setError(e.message))}>Refresh status</button></div><p className="text-xs text-[#7f7263]">“Accepted” confirms provider acceptance, not inbox delivery. Items needing review are held to avoid duplicate mail. Processing can be resumed if you leave this page.</p></>}
          <details><summary className="cursor-pointer text-sm font-semibold">Recipient list and delivery status</summary><div className="mt-3 max-h-64 space-y-2 overflow-auto">{detail.recipients.map(r=><div key={r.id} className="rounded-xl border p-3 text-sm">{r.full_name||r.email}<p className="text-xs text-[#7f7263]">{r.email} · {roleLabels[r.recipient_role]||"Team member"} · {r.status==="SENT"?"Accepted":r.status.toLowerCase()}{r.attempts?` · ${r.attempts} attempt(s)`:""}</p>{r.last_attempted_at&&<p className="text-xs">Last attempt: {new Date(r.last_attempted_at).toLocaleString()}</p>}{r.retry_succeeded_at&&<p className="text-xs">Retry accepted: {new Date(r.retry_succeeded_at).toLocaleString()}</p>}{r.last_error&&<p className="text-xs">{label(r.last_error)}</p>}{r.status==="FAILED"&&<p className="text-xs">Next retry: {new Date(r.next_attempt_at).toLocaleString()}</p>}</div>)}</div>{Object.values(detail.counts).reduce((a,b)=>a+b,0)>1000&&<p className="text-xs">Showing the first 1,000 recipients; totals include everyone.</p>}</details>
        </div>}
      </div>
      <aside className="space-y-3 rounded-[24px] border border-[#eadfce] bg-white p-5"><h3 className="font-semibold">Message history</h3><form className="space-y-2" onSubmit={e=>{e.preventDefault();setBusy(true);void refreshHistory(0).catch(e=>setError(e.message)).finally(()=>setBusy(false));}}><input aria-label="Search broadcast subject" className={field} placeholder="Search subject" value={filters.q||""} onChange={e=>setFilters(f=>({...f,q:e.target.value}))}/><details><summary className="cursor-pointer text-xs">More filters</summary><div className="mt-2 space-y-2">{[["status",["DRAFT","SCHEDULED","SENDING","COMPLETED","COMPLETED_WITH_ERRORS","CANCELLED"]],["audience",ANNOUNCEMENT_AUDIENCES],["category",TEMPLATE_CATEGORIES],["kind",["ANNOUNCEMENT","SURVEY","TESTIMONIAL"]]].map(([key,values])=><select key={key as string} aria-label={`Filter ${key}`} className={field} value={filters[key as string]||""} onChange={e=>setFilters(f=>({...f,[key as string]:e.target.value}))}><option value="">All {key}</option>{(values as readonly string[]).map(v=><option key={v} value={v}>{label(v)}</option>)}</select>)}{["from","to","sender","recipient"].map(k=><label key={k} className="block text-xs">{k==="from"?"Created from":k==="to"?"Created through":label(k)}<input className={field} type={k==="from"||k==="to"?"date":"text"} value={filters[k]||""} onChange={e=>setFilters(f=>({...f,[k]:e.target.value}))}/></label>)}</div></details><button className={button} disabled={busy}>Apply filters</button></form>{history.map(c=><button key={c.id} className="w-full rounded-xl border p-3 text-left disabled:opacity-50" disabled={busy} onClick={()=>void open(c)}><span className="block text-sm font-semibold">{c.subject||"Untitled draft"}</span><span className="mt-1 block text-xs text-[#7f7263]">{audienceLabels[c.audience]} · {label(c.status)} · {Object.values(c.counts||{}).reduce((a,b)=>a+b,0)} recipients</span><span className="block text-xs text-[#7f7263]">{c.scheduled_at?"Scheduled ":c.queued_at?"Confirmed ":"Created "}{new Date(c.scheduled_at||c.queued_at||c.created_at).toLocaleString()} · {c.counts?.SENT||0} accepted · {(c.counts?.FAILED||0)+(c.counts?.REVIEW||0)} failed / review</span></button>)}{!history.length&&<p className="text-sm text-[#7f7263]">No messages match these filters.</p>}<div className="flex gap-2"><button className={button} disabled={busy||offset===0} onClick={()=>void refreshHistory(Math.max(0,offset-50)).catch(e=>setError(e.message))}>Previous</button><button className={button} disabled={busy||!hasMore} onClick={()=>void refreshHistory(offset+50).catch(e=>setError(e.message))}>Next</button></div></aside>
    </div>
  </section>;
}
