begin;

create table if not exists public.help_assistant_requests (
  id bigint generated by default as identity primary key,
  profile_id uuid not null references public.profiles(id) on delete cascade,
  ip_hash text not null,
  created_at timestamptz not null default now()
);

create index if not exists help_assistant_requests_profile_created_idx
  on public.help_assistant_requests (profile_id, created_at desc);

create index if not exists help_assistant_requests_ip_created_idx
  on public.help_assistant_requests (ip_hash, created_at desc);

alter table public.help_assistant_requests enable row level security;
revoke all on table public.help_assistant_requests from anon, authenticated;

commit;
